### ISSUE TITLE
Inference Guide

### ISSUE THREAD

**Issue by irfanrah** [Enigma-li/Free2CAD#3]
Hello,
Firstly, I appreciate your commendable work on this project.

I've successfully set up the environment and verified it by running python train_AES_SG.py without any issues. Upon reviewing the supplementary material provided at [this link](https://geometry.cs.ucl.ac.uk/group_website/projects/2022/free2cad/paper_docs/Free2CAD_supl.pdf), I noticed the use of Fusion360 for testing. However, I'm uncertain about how to leverage your pretrained network within Fusion360.

Could you kindly provide detailed instructions on this? It would be of immense help.

Thank you!

**Comment by Enigma-li** [comment]
For the testing, we first extract the feature edges of Fusion360 models and render them into 2D sketches. These 2D sketches are fed as input to our network to obtain the prediction, which is further translated into the corresponding operation sequence as shown in the paper.

**Comment by irfanrah** [comment]
Hi, I have some follow up question.
1. I've successfully installed Fusion360 from [this link](https://www.autodesk.com/products/fusion-360/free-trial). However, in the video you shared at [this link](https://geometry.cs.ucl.ac.uk/group_website/projects/2022/free2cad/paper_docs/Free2CAD_video.mp4) (at the 2:29 timestamp), you demonstrated the ability to create a 3D isometric drawing with ease using your mouse. I apologize, but I'm relatively new to Fusion360. Could you kindly provide a detailed explanation of how to achieve the same result as demonstrated in your video?

2. Once I've followed the instructions from your response to my first question, could you please guide me through the process of rendering these 3D models into 2D sketches in Fusion360? Your detailed assistance would be greatly appreciated.
