### ISSUE TITLE
Command Sequences from provided Dataset into CAD

### ISSUE THREAD

**Issue by irfanrah** [Enigma-li/Free2CAD#5]
Hello,

I've successfully set up and executed the Fusion360 Python plugin available at [AutodeskAILab/Fusion360GalleryDataset](https://github.com/AutodeskAILab/Fusion360GalleryDataset). However, I am encountering two challenges:

Dataset Compatibility: I'm unsure how to modify the Fusion360GalleryDataset so that it becomes compatible with the format you require for your plugin or tool. Could you provide a step-by-step guide or outline the necessary transformations?

Command Sequences to CAD: I need detailed instructions on how to take the command sequences from the dataset provided and use them to generate the corresponding CAD models in Fusion360. A walkthrough on this process would be greatly appreciated.

![image](https://github.com/Enigma-li/Free2CAD/assets/20537982/7304782d-0f85-4c00-9823-e085b0224883)

**Comment by Enigma-li** [comment]
Please take a look of the issues from the Fusion360 dataset (#60 - #63), you may find it helpful. For example: https://github.com/AutodeskAILab/Fusion360GalleryDataset/issues/60
